---
- name: Clean fluentd
  hosts: demo
  tasks:
  - name: uninstall fluentd
    shell: yum remove td-agent

  - name: remove td-agent GPG key.
    rpm_key:
      state: absent
      key: gpg-pubkey-ab97acbe-586223cc
      

  - name: delete /etc/yum.repos.d/td.repo
    file: 
      state: absent
      path: /etc/yum.repos.d/td.repo
      