---
- name: Clean fluentd
  hosts: demo
  tasks:
  - name: yum remove td-agent
    yum:
      name: td-agent
      state: absent
    become: yes

  - name: remove td-agent GPG key.
    rpm_key:
      state: absent
      key: GPG-KEY-td-agent
    become: yes
      

  - name: delete /etc/yum.repos.d/td.repo
    file: 
      state: absent
      path: /etc/yum.repos.d/td.repo
    become: yes
      